name: Continious Integration for Multilevel Diacritizer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.10

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.4
  
    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Select environment
      run: poetry env info

    - name: Run tests
      run: python -m unittest discover tests/
